ConfigFiles = {
    'Latency'                :  "/Configuration/CMSIT.xml",
    'PixelAlive'             :  "/Configuration/CMSIT.xml",
    'NoiseScan'              :  "/Configuration/CMSIT.xml",
    'SCurveScan'             :  "/Configuration/CMSIT.xml",
    'GainScan'               :  "/Configuration/CMSIT.xml",
    'ThresholdEqualization'  :  "/Configuration/CMSIT.xml",
    'GainOptimization'       :  "/Configuration/CMSIT.xml",
    'ThresholdMinimization'  :  "/Configuration/CMSIT.xml",
    'ThresholdAdjustment'    :  "/Configuration/CMSIT.xml",
    'InjectionDelay'         :  "/Configuration/CMSIT.xml",
    'ClockDelay'             :  "/Configuration/CMSIT.xml",
    'Physics'                :  "/Configuration/CMSIT.xml",
    'AllScan'                :  "/Configuration/CMSIT.xml",
}