FESettings = {
'PA_IN_BIAS_LIN'        :  "350",
'PA_IN_BIAS_LIN'        :  "350",
'FC_BIAS_LIN'           :   "20",
'KRUM_CURR_LIN'         :   "29",
'LDAC_LIN'              :  "130",
'COMP_LIN'              :  "110",
'REF_KRUM_LIN'          :  "300",
'Vthreshold_LIN'        :  "400",

'PRMP_DIFF'             :  "511",
'FOL_DIFF'              :  "542",
'PRECOMP_DIFF'          :  "512",
'COMP_DIFF'             : "1023",
'VFF_DIFF'              :   "40",
'VTH1_DIFF'             :  "400",
'VTH2_DIFF'             :  "100",
'LCC_DIFF'              :   "20",
'CONF_FE_DIFF'          :    "0",

'IBIASP1_SYNC'          :   "80",
'IBIASP2_SYNC'          :  "120",
'IBIAS_SF_SYNC'         :   "80",
'IBIAS_KRUM_SYNC'       :   "55",
'IBIAS_DISC_SYNC'       :  "300",
'ICTRL_SYNCT_SYNC'      :  "100",
'VBL_SYNC'              :  "400",
'VTH_SYNC'              :  "200",
'VREF_KRUM_SYNC'        :  "450",

'VCAL_HIGH'             :  "600",
'VCAL_MED'              :  "100",

'GP_LVDS_ROUTE'         :    "0",
'LATENCY_CONFIG'        :  "136",
'CLK_DATA_DELAY'        :    "0",

'VOLTAGE_TRIM'          :  "528",

'ADC_MONITOR_CONFIG'    :    "5",
'BG_MONITOR_CONFIG'     :   "12",
'ADC_OFFSET_VOLT'       :   "63",
'ADC_MAXIMUM_VOLT'      :  "839",
'TEMPSENS_IDEAL_FACTOR' : "1225",
'FC_BIAS_LIN'           :   "20",
'KRUM_CURR_LIN'         :   "29",
'LDAC_LIN'              :  "130",
'COMP_LIN'              :  "110",
'REF_KRUM_LIN'          :  "300",
'Vthreshold_LIN'        :  "400",

'PRMP_DIFF'             :  "511",
'FOL_DIFF'              :  "542",
'PRECOMP_DIFF'          :  "512",
'COMP_DIFF'             : "1023",
'VFF_DIFF'              :   "40",
'VTH1_DIFF'             :  "400",
'VTH2_DIFF'             :  "100",
'LCC_DIFF'              :   "20",
'CONF_FE_DIFF'          :    "0",

'IBIASP1_SYNC'          :   "80",
'IBIASP2_SYNC'          :  "120",
'IBIAS_SF_SYNC'         :   "80",
'IBIAS_KRUM_SYNC'       :   "55",
'IBIAS_DISC_SYNC'       :  "300",
'ICTRL_SYNCT_SYNC'      :  "100",
'VBL_SYNC'              :  "400",
'VTH_SYNC'              :  "200",
'VREF_KRUM_SYNC'        :  "450",

'VCAL_HIGH'             :  "600",
'VCAL_MED'              :  "100",

'GP_LVDS_ROUTE'         :    "0",
'LATENCY_CONFIG'        :  "136",
'CLK_DATA_DELAY'        :    "0",

'VOLTAGE_TRIM'          :  "528",

'ADC_MONITOR_CONFIG'    :    "5",
'BG_MONITOR_CONFIG'     :   "12",
'ADC_OFFSET_VOLT'       :   "63",
'ADC_MAXIMUM_VOLT'      :  "839",
'TEMPSENS_IDEAL_FACTOR' : "1225",
}


FESettings_Dict = {
	'Latency'					:	FESettings,
	'PixelAlive'				:	FESettings,
    'NoiseScan'					:   FESettings,
	'GainScan'					:	FESettings,
	'SCurveScan'				:	FESettings,
	'ThresholdEqualization'		:	FESettings,
	'GainOptimization'			:	FESettings,
	'ThresholdMinimization'		:	FESettings,
	'ThresholdAdjustment'		:	FESettings,
	'InjectionDelay'			:	FESettings,
	'ClockDelay'				:	FESettings,
	'Physics'					:	FESettings,
}
