#ifndef __FILE_DEFINITIONS_H__
#define __FILE_DEFINITIONS_H__

#define OUTPUT_CONFIGURATION_FILE "Configuration.xml"

// Nodes
#define HW_DESCRIPTION_NODE_NAME "HwDescription"
#define BEBOARD_NODE_NAME "BeBoard"
#define BEBOARD_CONNECTION_NODE_NAME "connection"
#define BEBOARD_CONFIGURATION_NODE_NAME "configuration"
#define BEBOARD_CDCE_NODE_NAME "CDCE"
#define BEBOARD_REGISTER_NODE_NAME "Register"

#define OPTICALGROUP_NODE_NAME "OpticalGroup"
#define NTCPROPERTIES_NODE_NAME "NTCProperties"
#define LPGBT_FILES_NODE_NAME "lpGBT_Files"
#define LPGBT_CONFIGFILE_NODE_NAME "lpGBT_ConfigFile"
#define LPGBT_NODE_NAME "lpGBT"
#define VTRX_NODE_NAME "VTRx"
#define VTRX_FILES_NODE_NAME "VTRx_Files"

#define HYBRID_NODE_NAME "Hybrid"
#define CHIP_FILES_APPEND_NODE_NAME "_Files"
#define CIC2_NODE_NAME "CIC2"
#define CBC_NODE_NAME "CBC"
#define MPA2_NODE_NAME "MPA2"
#define SSA2_NODE_NAME "SSA2"
#define RD53_NODE_NAME "RD53"
#define RD53_LANECONFIG_NAME "LaneConfig"
#define RD53A_NODE_NAME "RD53A"
#define RD53Bv1_NODE_NAME "RD53Bv1"
#define RD53Bv2_NODE_NAME "RD53Bv2"
#define LPGBT_PHASES_FOR_CIC_BYPASS_MAIN_NODE_NAME "LpGBTphaseForCICbypass"
#define LPGBT_PHASES_FOR_CIC_BYPASS_PHYPORT_NODE_NAME "LpGBTphaseForCICbypassPhyPort"
#define CHIP_GLOBAL_NODE_NAME "Global"

#define SETTINGS_NODE_NAME "Settings"
#define SETTING_NODE_NAME "Setting"

#define MONITORINGSETTINGS_NODE_NAME "MonitoringSettings"
#define MONITORING_NODE_NAME "Monitoring"
#define MONITORINGSLEEPTIME_NODE_NAME "MonitoringSleepTime"
#define MONITORINGELEMENT_NODE_NAME "MonitoringElement"

#define COMMUNICATIONSETTINGS_NODE_NAME "CommunicationSettings"
#define COMMUNICATIONSETTINGS_CONTROLLER_NODE_NAME "Controller"
#define COMMUNICATIONSETTINGS_DQM_NODE_NAME "DQM"
#define COMMUNICATIONSETTINGS_MONITORDQM_NODE_NAME "MonitorDQM"
#define COMMUNICATIONSETTINGS_POWERSUPPLYCLIENT_NODE_NAME "PowerSupplyClient"

#define BEBOARDREGISTER_NODE_NAME "BeBoardRegister"

// Common attributes
#define COMMON_ID_ATTRIBUTE_NAME "Id"
#define COMMON_RESET_ATTRIBUTE_NAME "reset"
#define COMMON_PATH_ATTRIBUTE_NAME "path"
#define COMMON_FILENAME_ATTRIBUTE_NAME "fileName"
#define COMMON_CONFIGFILE_ATTRIBUTE_NAME "configFile"
#define COMMON_NAME_ATTRIBUTE_NAME "name"
#define COMMON_ENABLE_ATTRIBUTE_NAME "enable"

// BeBoard attubutes
#define BEBOARD_TYPE_ATTRIBUTE_NAME "boardType"
#define BEBOARD_EVENT_TYPE_ATTRIBUTE_NAME "eventType"
#define BEBOARD_LINKRESET_ATTRIBUTE_NAME "linkReset"
#define BEBOARD_BOARDRESET_ATTRIBUTE_NAME "boardReset"
#define BEBOARD_CONFIGURE_ATTRIBUTE_NAME "configure"
#define BEBOARD_COMMENT_ATTRIBUTE_NAME "comment"

// BeBoard connection attributes
#define BEBOARD_CONNECTION_ID_ATTRIBUTE_NAME "id"
#define BEBOARD_CONNECTION_URI_ATTRIBUTE_NAME "uri"
#define BEBOARD_CONNECTION_ADDRESS_TABLE_ATTRIBUTE_NAME "address_table"

// BeBoard configuration attributes
#define BEBOARD_CONFIGURATION_FILE_NAME_ATTRIBUTE_NAME "file_name"

// BeBoard CDCE attributes
#define BEBOARD_CDCE_CONFIGURE_ATTRIBUTE_NAME "configure"
#define BEBOARD_CDCE_CLOCKRATE_ATTRIBUTE_NAME "clockRate"

// OpticalGroup attributes
#define OPTICALGROUP_FMCID_ATTRIBUTE_NAME "FMCId"

// NTCProperties attributes
#define NTCPROPERTIES_TYPE_ATTRIBUTE_NAME "type"
#define NTCPROPERTIES_ADC_ATTRIBUTE_NAME "ADC"
#define NTCPROPERTIES_LOOKUPTABLE_ATTRIBUTE_NAME "lookUpTable"

// LpGBT attributes
#define LPGBT_VERSION_ATTRIBUTE_NAME "version"
#define LPGBT_OPTICAL_ATTRIBUTE_NAME "optical"

// LpGBT phases for CIC bypassPort
#define LPGBT_PHASES_FOR_CIC_BYPASS_LINE_ATTRIBUTE_NAME "LpGBTphaseForCICbypassPhyPort"

// Chip attibutes
#define CHIP_NOISE_ATTRIBUTE_NAME "noise"
#define CHIP_PEDESTAL_ATTRIBUTE_NAME "pedestal"
#define CHIP_ADC_SLOPE_ATTRIBUTE_NAME "ADCslope"                   // for PS chips only
#define CHIP_ADC_OFFSET_ATTRIBUTE_NAME "ADCoffset"                 // for PS chips only
#define CHIP_TEMPERATURE_SLOPE_ATTRIBUTE_NAME "TemperatureSlope"   // for PS chips only
#define CHIP_TEMPERATURE_OFFSET_ATTRIBUTE_NAME "TemperatureOffset" // for PS chips only

// Monitoring attributes
#define MONITORING_NODE_TYPE_ATTRIBUTE_NAME "type"
#define MONITORING_NODE_ENABLE_ATTRIBUTE_NAME "enable"
#define MONITORING_NODE_SILENTRUN_ATTRIBUTE_NAME "silentRunning"
#define MONITORINGELEMENT_DEVICE_ATTRIBUTE_NAME "device"
#define MONITORINGELEMENT_REGISTER_ATTRIBUTE_NAME "register"

// Communication Settings attributes
#define COMMUNICATIONSETTINGS_IP_ATTRIBUTE_NAME "ip"
#define COMMUNICATIONSETTINGS_PORT_ATTRIBUTE_NAME "port"
#define COMMUNICATIONSETTINGS_ENABLECONNECTION_ATTRIBUTE_NAME "enableConnection"

// BeBoard values
#define BEBOARD_TYPE_ATTRIBUTE_D19C_VALUE "D19C"
#define BEBOARD_TYPE_ATTRIBUTE_RD53_VALUE "RD53"
#define BEBOARD_EVENT_TYPE_ATTRIBUTE_ZS_VALUE "ZS"
#define BEBOARD_EVENT_TYPE_ATTRIBUTE_PSAS_VALUE "PSAS"
#define BEBOARD_EVENT_TYPE_ATTRIBUTE_VR2S_VALUE "VR2S"
#define BEBOARD_EVENT_TYPE_ATTRIBUTE_VR_VALUE "VR"
#define BEBOARD_EVENT_TYPE_ATTRIBUTE_VRPCTestAdapter_VALUE "VRPCTestAdapter"

// OpticalGroup values
#define OPTICALGROUP_FMCID_ATTRIBUTE_L12_VALUE "L12"
#define OPTICALGROUP_FMCID_ATTRIBUTE_L8_VALUE "L8"

// Monitoring type values
#define MONITORING_NODE_TYPE_ATTRIBUTE_NONE_VALUE "None"
#define MONITORING_NODE_TYPE_ATTRIBUTE_2S_VALUE "2S"
#define MONITORING_NODE_TYPE_ATTRIBUTE_RD53A_VALUE "RD53A"
#define MONITORING_NODE_TYPE_ATTRIBUTE_RD53B_VALUE "RD53B"
#define MONITORING_NODE_TYPE_ATTRIBUTE_2SSEH_VALUE "2SSEH"
#define MONITORING_NODE_TYPE_ATTRIBUTE_PS_VALUE "PS"

#endif
