constexpr const char* errorList[] = {"Unkown command",
                                     "Unkown parameter",
                                     "Index out of range",
                                     "Not enough arguments",
                                     "Privilege level requirements not met",
                                     "Saving error on device",
                                     "Invalid password",
                                     "Power supply in fault",
                                     "Power supply already ON",
                                     "Setpoint is set out of model limits",
                                     "Setpoint is set out of software limits",
                                     "Setpoint is not a number",
                                     "Module is OFF",
                                     "Slew rate out of limits",
                                     "Device is set in local mode",
                                     "Module is not in waveform mode",
                                     "Module is in waveform mode",
                                     "Device is set in remote mode",
                                     "Module is already in the selected loop mode",
                                     "Module is not in the selected loop mode",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Error not defined",
                                     "Unkown error"}; /*!< Array with the description of the errors */
