name: Continuous Integration Docker

on:
  pull_request:
    branches:
      - DEV
  workflow_dispatch:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.OSU_PIXELS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.OSU_PIXELS_DOCKERHUB_PASSWORD }}

      - name: Docker Login to GitLab Registry
        run: |
          docker login -u ${{ secrets.DOCKER_LOGIN_USERNAME}} -p ${{ secrets.DOCKER_LOGIN_PASSWORD }} gitlab-registry.cern.ch

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: osupixels/test:latest
