name: ci

on:
  push:
    branches:
      - DEV
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: osupixels
          password: phase2pixels

      - name: Docker build
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: osupixels/ph2_acf_gui_dev:latest